export const JOURNAL_ENTRY_STATUSES = [
  {
    key: 'DRAFT',
    label: 'Draft',
    color: '#6B7280',
    description: 'Entry created but not yet posted to the ledger',
    allowEdit: true,
    allowDelete: true,
    allowPost: true,
    allowVoid: false,
    allowReverse: false,
    allowDuplicate: true,
  },
  {
    key: 'POSTED',
    label: 'Posted',
    color: '#10B981',
    description: 'Entry posted to the ledger — account balances updated',
    allowEdit: false,
    allowDelete: false,
    allowPost: false,
    allowVoid: true,
    allowReverse: true,
    allowDuplicate: true,
  },
  {
    key: 'VOID',
    label: 'Void',
    color: '#1F2937',
    description: 'Entry voided — balance impact reversed',
    allowEdit: false,
    allowDelete: false,
    allowPost: false,
    allowVoid: false,
    allowReverse: false,
    allowDuplicate: true,
  },
];
