export const EXPENSE_STATUS_INFO = {
  DRAFT: {
    label: 'Draft',
    color: '#6B7280',
    description: 'Expense is being prepared and has not been submitted',
    allowEdit: true,
    allowDelete: true,
    allowSubmit: true,
    allowApprove: false,
    allowReject: false,
    allowMarkPaid: false,
    allowVoid: false,
  },
  PENDING_APPROVAL: {
    label: 'Pending Approval',
    color: '#F59E0B',
    description: 'Expense has been submitted and is awaiting approval',
    allowEdit: false,
    allowDelete: false,
    allowSubmit: false,
    allowApprove: true,
    allowReject: true,
    allowMarkPaid: false,
    allowVoid: true,
  },
  APPROVED: {
    label: 'Approved',
    color: '#3B82F6',
    description: 'Expense has been approved and is awaiting payment',
    allowEdit: false,
    allowDelete: false,
    allowSubmit: false,
    allowApprove: false,
    allowReject: false,
    allowMarkPaid: true,
    allowVoid: true,
  },
  REJECTED: {
    label: 'Rejected',
    color: '#EF4444',
    description: 'Expense was rejected and sent back for revision',
    allowEdit: true,
    allowDelete: true,
    allowSubmit: false,
    allowApprove: false,
    allowReject: false,
    allowMarkPaid: false,
    allowVoid: false,
  },
  PAID: {
    label: 'Paid',
    color: '#10B981',
    description: 'Expense has been paid by the company',
    allowEdit: false,
    allowDelete: false,
    allowSubmit: false,
    allowApprove: false,
    allowReject: false,
    allowMarkPaid: false,
    allowVoid: true,
  },
  REIMBURSED: {
    label: 'Reimbursed',
    color: '#8B5CF6',
    description: 'Employee has been reimbursed for this expense',
    allowEdit: false,
    allowDelete: false,
    allowSubmit: false,
    allowApprove: false,
    allowReject: false,
    allowMarkPaid: false,
    allowVoid: true,
  },
  VOID: {
    label: 'Void',
    color: '#9CA3AF',
    description: 'Expense has been voided and is no longer valid',
    allowEdit: false,
    allowDelete: false,
    allowSubmit: false,
    allowApprove: false,
    allowReject: false,
    allowMarkPaid: false,
    allowVoid: false,
  },
};
