export const PURCHASE_ORDER_STATUS_INFO = {
  DRAFT: {
    label: 'Draft',
    color: '#6B7280',
    description: 'Purchase order is being prepared and has not been sent to vendor',
    allowEdit: true,
    allowDelete: true,
    allowSend: true,
    allowReceive: false,
    allowConvert: false,
    allowClose: false,
    allowVoid: false,
  },
  SENT: {
    label: 'Sent',
    color: '#3B82F6',
    description: 'Purchase order has been sent to the vendor',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowReceive: true,
    allowConvert: false,
    allowClose: false,
    allowVoid: true,
  },
  PARTIAL: {
    label: 'Partially Received',
    color: '#F59E0B',
    description: 'Some items from this purchase order have been received',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowReceive: true,
    allowConvert: true,
    allowClose: true,
    allowVoid: true,
  },
  RECEIVED: {
    label: 'Received',
    color: '#10B981',
    description: 'All items from this purchase order have been received',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowReceive: false,
    allowConvert: true,
    allowClose: true,
    allowVoid: false,
  },
  CLOSED: {
    label: 'Closed',
    color: '#059669',
    description: 'Purchase order has been closed (converted to bill or manually closed)',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowReceive: false,
    allowConvert: false,
    allowClose: false,
    allowVoid: false,
  },
  VOID: {
    label: 'Void',
    color: '#9CA3AF',
    description: 'Purchase order has been cancelled and is no longer valid',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowReceive: false,
    allowConvert: false,
    allowClose: false,
    allowVoid: false,
  },
};
