export const ESTIMATE_STATUS_INFO = {
  DRAFT: {
    label: 'Draft',
    color: '#6B7280',
    description: 'Estimate is being prepared and has not been sent',
    allowEdit: true,
    allowDelete: true,
    allowSend: true,
    allowAccept: false,
    allowReject: false,
    allowConvert: false,
    allowVoid: false,
  },
  SENT: {
    label: 'Sent',
    color: '#3B82F6',
    description: 'Estimate has been sent to the customer',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowAccept: true,
    allowReject: true,
    allowConvert: false,
    allowVoid: true,
  },
  VIEWED: {
    label: 'Viewed',
    color: '#8B5CF6',
    description: 'Customer has viewed the estimate',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowAccept: true,
    allowReject: true,
    allowConvert: false,
    allowVoid: true,
  },
  ACCEPTED: {
    label: 'Accepted',
    color: '#10B981',
    description: 'Customer has accepted the estimate',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowAccept: false,
    allowReject: false,
    allowConvert: true,
    allowVoid: true,
  },
  REJECTED: {
    label: 'Rejected',
    color: '#EF4444',
    description: 'Customer has rejected the estimate',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowAccept: false,
    allowReject: false,
    allowConvert: false,
    allowVoid: false,
  },
  EXPIRED: {
    label: 'Expired',
    color: '#F59E0B',
    description: 'Estimate has passed its expiration date',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowAccept: false,
    allowReject: false,
    allowConvert: false,
    allowVoid: false,
  },
  CONVERTED: {
    label: 'Converted',
    color: '#059669',
    description: 'Estimate has been converted to an invoice',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowAccept: false,
    allowReject: false,
    allowConvert: false,
    allowVoid: false,
  },
  VOID: {
    label: 'Void',
    color: '#9CA3AF',
    description: 'Estimate has been voided and is no longer valid',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowAccept: false,
    allowReject: false,
    allowConvert: false,
    allowVoid: false,
  },
};
