export const BILL_STATUS_INFO = {
  DRAFT: {
    label: 'Draft',
    color: '#6B7280',
    description: 'Bill is being prepared and has not been received',
    allowEdit: true,
    allowDelete: true,
    allowReceive: true,
    allowVoid: false,
    allowPayment: false,
  },
  RECEIVED: {
    label: 'Received',
    color: '#3B82F6',
    description: 'Bill has been received from the vendor and is awaiting payment',
    allowEdit: false,
    allowDelete: false,
    allowReceive: false,
    allowVoid: true,
    allowPayment: true,
  },
  PARTIALLY_PAID: {
    label: 'Partially Paid',
    color: '#F59E0B',
    description: 'A partial payment has been made toward this bill',
    allowEdit: false,
    allowDelete: false,
    allowReceive: false,
    allowVoid: true,
    allowPayment: true,
  },
  PAID: {
    label: 'Paid',
    color: '#10B981',
    description: 'Bill has been fully paid',
    allowEdit: false,
    allowDelete: false,
    allowReceive: false,
    allowVoid: false,
    allowPayment: false,
  },
  OVERDUE: {
    label: 'Overdue',
    color: '#EF4444',
    description: 'Bill is past its due date and not fully paid',
    allowEdit: false,
    allowDelete: false,
    allowReceive: false,
    allowVoid: true,
    allowPayment: true,
  },
  VOID: {
    label: 'Void',
    color: '#9CA3AF',
    description: 'Bill has been voided and is no longer valid',
    allowEdit: false,
    allowDelete: false,
    allowReceive: false,
    allowVoid: false,
    allowPayment: false,
  },
};
