export const CREDIT_NOTE_STATUS_INFO = {
  DRAFT: {
    label: 'Draft',
    color: '#6B7280',
    description: 'Credit note is being prepared and has not been issued',
    allowEdit: true,
    allowDelete: true,
    allowOpen: true,
    allowApply: false,
    allowRefund: false,
    allowVoid: false,
  },
  OPEN: {
    label: 'Open',
    color: '#3B82F6',
    description: 'Credit note has been issued and is available to apply or refund',
    allowEdit: false,
    allowDelete: false,
    allowOpen: false,
    allowApply: true,
    allowRefund: true,
    allowVoid: true,
  },
  PARTIALLY_APPLIED: {
    label: 'Partially Applied',
    color: '#F59E0B',
    description: 'Part of the credit has been applied to invoices or refunded',
    allowEdit: false,
    allowDelete: false,
    allowOpen: false,
    allowApply: true,
    allowRefund: true,
    allowVoid: true,
  },
  APPLIED: {
    label: 'Fully Applied',
    color: '#10B981',
    description: 'Credit note has been fully applied or refunded',
    allowEdit: false,
    allowDelete: false,
    allowOpen: false,
    allowApply: false,
    allowRefund: false,
    allowVoid: false,
  },
  VOID: {
    label: 'Void',
    color: '#9CA3AF',
    description: 'Credit note has been voided and is no longer valid',
    allowEdit: false,
    allowDelete: false,
    allowOpen: false,
    allowApply: false,
    allowRefund: false,
    allowVoid: false,
  },
};
