export const INVOICE_STATUS_INFO = {
  DRAFT: {
    label: 'Draft',
    color: '#6B7280',
    description: 'Invoice is being prepared and has not been sent',
    allowEdit: true,
    allowDelete: true,
    allowSend: true,
    allowVoid: false,
    allowPayment: false,
  },
  SENT: {
    label: 'Sent',
    color: '#3B82F6',
    description: 'Invoice has been sent to the customer',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowVoid: true,
    allowPayment: true,
  },
  PARTIALLY_PAID: {
    label: 'Partially Paid',
    color: '#F59E0B',
    description: 'Customer has made a partial payment',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowVoid: true,
    allowPayment: true,
  },
  PAID: {
    label: 'Paid',
    color: '#10B981',
    description: 'Invoice has been fully paid',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowVoid: false,
    allowPayment: false,
  },
  OVERDUE: {
    label: 'Overdue',
    color: '#EF4444',
    description: 'Invoice is past its due date and not fully paid',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowVoid: true,
    allowPayment: true,
  },
  VOID: {
    label: 'Void',
    color: '#9CA3AF',
    description: 'Invoice has been voided and is no longer valid',
    allowEdit: false,
    allowDelete: false,
    allowSend: false,
    allowVoid: false,
    allowPayment: false,
  },
};
